# Project2-Compose: Jenkins + Docker-in-Docker (DinD) via TLS
# - DinD runs a Docker daemon securely with TLS
# - Jenkins talks to DinD as a remote Docker host
# - Named volumes persist Jenkins data and Docker layer cache

name: project2-compose

services:
  dind:
    image: docker:26-dind
    container_name: project2-compose-dind
    privileged: true                  # DinD needs privileged to start dockerd inside the container
    environment:
      - DOCKER_TLS_CERTDIR=/certs     # Auto-generate TLS server/client certs under /certs
    command:
      - --host=tcp://0.0.0.0:2376     # Expose Docker daemon over TLS on 2376 for remote clients (Jenkins)
      - --host=unix:///var/run/docker.sock   # Keep local Unix socket (used by healthcheck)
      - --storage-driver=overlay2     # Stable storage driver for layer caching
    volumes:
      - docker_cache:/var/lib/docker  # Named volume: Docker layer cache (speeds builds)
      - docker_certs:/certs           # Share TLS certs with Jenkins
    networks:
      - jenkins
    healthcheck:
      test: ["CMD", "docker", "info"] # Healthy when the daemon responds
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  jenkins:
    build:
      context: ./jenkins              # Dockerfile adds Docker CLI into Jenkins image
    container_name: project2-compose-jenkins
    ports:
      - "8080:8080"                   # Jenkins UI
      - "50000:50000"                 # Inbound agent port
    environment:
      - DOCKER_HOST=tcp://dind:2376   # Jenkins' Docker CLI talks to DinD over TLS
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client # Path to client certs generated by DinD
      - JENKINS_OPTS=--prefix=/
      - JAVA_OPTS=-Xms256m -Xmx512m   # Prevent OOM on smaller hosts
    volumes:
      - jenkins_home:/var/jenkins_home # Persist Jenkins jobs/config/plugins
      - docker_certs:/certs:ro         # Mount certs read-only; client certs available at /certs/client
    depends_on:
      dind:
        condition: service_healthy     # Start Jenkins only after Docker daemon is healthy
    networks:
      - jenkins
    restart: unless-stopped

networks:
  jenkins:

volumes:
  jenkins_home:   # Jenkins data (config, jobs, plugins)
  docker_cache:   # Docker layer cache to speed builds
  docker_certs:   # Shared TLS certs for secure DinD access
