
services:
  dind:
    image: docker:27-dind
    container_name: dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    command:
      - "--host=tcp://0.0.0.0:2376"
      - "--host=unix:///var/run/docker.sock"
      - "--storage-driver=overlay2"
    ports:
      - "2376:2376"
    volumes:
      - docker_certs:/certs
      - docker_data:/var/lib/docker
    restart: unless-stopped
    networks:
      - jenkins_net

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    depends_on:
      - dind
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - docker_certs:/certs/client:ro
    user: "0"
    restart: unless-stopped
    networks:
      - jenkins_net

volumes:
  jenkins_home:
  docker_data:
  docker_certs:

networks:
  jenkins_net:
    driver: bridge
