version: "3.9"

services:
  dind:
    image: docker:27-dind
    container_name: dind
    privileged: true                         # required by dockerd-in-docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs            # auto-generate TLS certs
    command:
      - "--host=tcp://0.0.0.0:2376"          # TLS-secured remote API
      - "--host=unix:///var/run/docker.sock" # local socket for healthcheck/ops
      - "--storage-driver=overlay2"
    ports:
      - "2376:2376"                          # expose TLS Docker API
    volumes:
      - docker_certs:/certs                  # server+client certs
      - docker_data:/var/lib/docker          # layer/cache data
    healthcheck:
      # Simple & reliable: check dockerd via local Unix socket
      test: ["CMD-SHELL", "docker -H unix:///var/run/docker.sock version >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    restart: unless-stopped
    networks:
      - jenkins_net

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    depends_on:
      dind:
        condition: service_healthy
    environment:
      - DOCKER_HOST=tcp://dind:2376          # talk to DinD over TLS
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - "8080:8080"                          # Jenkins UI
      - "50000:50000"                        # inbound agents
    volumes:
      - jenkins_home:/var/jenkins_home       # persist Jenkins state
      - docker_certs:/certs/client:ro        # client certs (read-only)
    user: "0"                                 # ensure access to mounted certs
    restart: unless-stopped
    networks:
      - jenkins_net

volumes:
  jenkins_home:
  docker_data:
  docker_certs:

networks:
  jenkins_net:
    driver: bridge
