name: project2-compose

services:
  docker:
    image: docker:26-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker_data:/var/lib/docker
      - docker_certs:/certs                # DinD writes client/server certs here
      - jenkins_home:/var/jenkins_home     # <-- RW so DinD can bind-mount workspaces
    networks: [ci_net]

  jenkins:
    build: ./jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client      # client certs live under /certs/client
      DOCKER_TLS_VERIFY: "1"
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - docker
    volumes:
      - jenkins_home:/var/jenkins_home     # Jenkins home (workspace lives here)
      - docker_certs:/certs:ro             # mount the WHOLE certs tree (cleaner)
    networks: [ci_net]

volumes:
  docker_data:
  docker_certs:
  jenkins_home:

networks:
  ci_net:
    driver: bridge*
